### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nickwinn** [softegg/supercon-2023-badge-enclosure#3]
Overall the case is good, would recommend adding a method of easily changing the batteries (like a snap on back that isn't screwed on).

**Comment by softegg** [comment]
Hey, the files are all here for you!
Feel free to fork the project and add the features you want!

**Comment by softegg** [comment]
I'm gonna mark this as closed because I don't really intend to make any changes at this point. This badge design is a jumping off point for the user to make their own changes, and I encourage everybody to fork the project and do just that.
Please share your changes on GitHub when you do!
